### ISSUE TITLE
Issue with handling large osrm file

### ISSUE THREAD

**Issue by swadhin-** [osrmnet/osrmnet#78]
I have built osrm backend version 5.22 for windows and extracted the data. For small areas it works but for large areas it fails saying some files are missing. I tried running the extracted files with osrm-routed and it works without any issue. So the error is not on osrm-backend side.

I extracted and tried to run this data -
https://download.geofabrik.de/asia/bangladesh.html

Windows Build -
[OSRM v5.22](https://drive.google.com/file/d/1Bhpn17NijVXpyDzdw1ZuOsDeDJEQgRYr/view?usp=sharing)

**Comment by ssuluh** [comment]
Do you have exact error ? Just missing files is rather generic.

**Comment by swadhin-** [comment]
`Osrmnet.OsrmException : Required files are missing, cannot continue.  Have all the pre-processing steps been run?`

The error it self is rather generic. It doesn't mention what file or what's missing and doesn't appear for smaller data sets. Also the data extraction is not at fault cause osrm-routed is able to run it properly

**Comment by ssuluh** [comment]
@swadhin- 

I can not reproduce your issue.  Created a .NET6 console app and pre process [bangladesh-latest](https://download.geofabrik.de/asia/bangladesh-latest.osm.pbf) using official 5.22 redistributable. Algorithm is set for MLD.

See below:
![image](https://user-images.githubusercontent.com/12562475/150697953-99d366ef-aff9-4c3e-b39b-0d406d59801e.png)

You can also get osrmnet official 5.22 build (osrm does not maintain windows build) by:
1. Cloning this project
2. Run this command from powershell:
`.\build.ps1 -Target "GetDependencies"`
3. Location of the osrm libraries and app: .\osrmnet\src\osrm.net\libosrm\redist\osrm_15.22.0.zip

What I would do:
1. Re-check your code and the environment per requirement of both osrm and osrmnet.
2. Reprocess the osm file again this time with the 5.22 obtained above (I can't guarantee any other build of "osrm" out there)

**Comment by swadhin-** [comment]
Thanks, Let me try to build it using the build.ps1 file

**Comment by swadhin-** [comment]
I was able to run it without any issues. Thanks !!
